name: ML SVM Model CI Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Run the workflow on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Setup Python environment
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install required Python packages

      - name: Run SVM model script
        run: |
          python practical_model_python_script.py  # Run your SVM model script
          
      - name: Run tests (optional)
        run: |
          pytest  # Run tests if you have a test suite
